### PR TITLE
Create sv.json

### PR DESCRIPTION
**Pull request by el97**
Added Swedish translation

### CODE REVIEW

**Comment by ralberth** [comment]
Would you please add this file to the return value for getTranslations() in MMM-MinecraftStatus.js?  The code will not detect the new sv.json file automatically.   Thanks.

**Comment by el97** [comment]
Not sure if i did it right... Im new to github.

**Comment by ralberth** [comment]
Great job!  I merged this onto mainline so everyone can use it.  Thanks for a great feature addition to the module.

**Comment by el97** [comment]
I forgot to add the swedish in the translations on the readme file. Can you do it or should i?

**Comment by ralberth** [comment]
I posted the change to README.md: said thanks to you with a pointer to your github page.

**Pull request merged**
